---
apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSModelRef
metadata:
  name: gpt-oss-20b
  namespace: models-as-a-service
spec:
  modelRef:
    kind: LLMInferenceService
    name: gpt-oss-20b-maas
---
apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSModelRef
metadata:
  name: nemotron-14b
  namespace: models-as-a-service
spec:
  modelRef:
    kind: LLMInferenceService
    name: nemotron-14b-maas
